version: "3.8"
services:
  api:
    image: yardenshoham/sow-rest-api
    restart: unless-stopped
  ui:
    image: yardenshoham/sow-rest-ui
    restart: unless-stopped
    depends_on:
      - api
  reverse-proxy:
    image: nginx:alpine
    restart: unless-stopped
    environment:
      - NGINX_ENTRYPOINT_QUIET_LOGS=1
    ports:
      - 80:80
    depends_on:
      - api
      - ui
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
