# This is a basic workflow to help you get started with Actions

name: CI
# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  workflow_dispatch:
  push:
    branches: [ main, github_actions ]
    paths-ignore: 
      - 'diagrams/**'

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  build-and-release-ova:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    strategy:
      fail-fast: true
      matrix:
        region: ["eu-west-2", "eu-west-1"]
    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:

    # Checks-out your repository under $GITHUB_WORKSPACE/vmware-scripts, so your job can access it  
    - uses: actions/checkout@v2

    # build artifact
    - name: Build Artifact
      uses: operatehappy/packer-github-actions@master
      with:
        command: build
        arguments: "-color=false -on-error=cleanup -var github_sha=${{ github.sha }} -var vm_name=k8-rebuild -var region=${{ matrix.region }} -var aws_access_key=${{ secrets.AWS_ACCESS_KEY }} -var aws_secret_key=${{ secrets.AWS_SECRET_ACCESS_KEY }}"
        target: packer/aws-ova.json

